version: '3.8'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile # shares same dockerfile
    expose:
      - 5000
    env_file:
      - ./.env.prod 
    volumes:
      - ./flask/:/usr/src/app/
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - 443:443
    depends_on:
      - web
    volumes:
      - ./nginx/certs:/etc/nginx/certs
