version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: flask run -h 0.0.0.0
    # command: gunicorn --bind 0.0.0.0:5000 create_app:app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - ./flask/:/usr/src/app/
