version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: flask run
    ports:
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - ./flask/:/usr/src/app/
